# Generated by Django 3.2.8 on 2022-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecture_id", models.IntegerField()),
                ("title", models.CharField(max_length=250)),
                ("date", models.DateField()),
                ("corporate_author", models.CharField(max_length=250)),
                ("abstract", models.TextField()),
                ("series", models.CharField(max_length=250)),
                ("speaker", models.CharField(blank=True, max_length=250)),
                ("speaker_details", models.CharField(blank=True, max_length=250)),
                ("event_details", models.CharField(blank=True, max_length=250)),
                ("thumbnail_picture", models.TextField()),
                ("language", models.CharField(max_length=3)),
                ("subject_category", models.CharField(max_length=520)),
                ("lecture_note", models.DateTimeField(blank=True)),
                ("imprint", models.CharField(max_length=250)),
                ("license", models.CharField(max_length=250)),
            ],
        ),
    ]
