# Generated by Django 3.2.8 on 2021-10-22 09:59

import cds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("lecture_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("corporateAuthor", models.CharField(max_length=100)),
                ("abstract", models.CharField(max_length=3000)),
                ("series", models.CharField(max_length=50)),
                ("speaker", models.CharField(max_length=50)),
                ("speakerDetails", models.CharField(max_length=50)),
                ("eventDetails", models.CharField(max_length=50)),
                (
                    "thumbnailPicture",
                    models.FilePathField(path=cds.models.thumbnail_path),
                ),
                ("language", models.CharField(max_length=3)),
                ("subjectCategory", models.CharField(max_length=50)),
                ("lectureNote", models.DateTimeField()),
                ("imprint", models.DurationField()),
                ("license", models.CharField(max_length=30)),
            ],
        ),
    ]
