# Generated by Django 3.2.8 on 2022-05-31 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="sponsor",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lecture_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="subject_category",
            field=models.CharField(max_length=250),
        ),
    ]
