# Generated by Django 3.2.8 on 2022-05-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="lecture_id",
            field=models.IntegerField(unique=True),
        ),
    ]
