# Generated by Django 3.2.8 on 2022-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0002_alter_lecture_imprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="corporate_author",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="event_details",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="imprint",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="license",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="series",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="speaker",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="speaker_details",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="subject_category",
            field=models.CharField(max_length=520),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
