# Generated by Django 3.2.8 on 2022-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0002_auto_20220531_1405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="thumbnail_picture",
            field=models.TextField(blank=True),
        ),
    ]
