# Generated by Django 3.2.8 on 2022-06-02 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0003_alter_lecture_thumbnail_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="files",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="abstract",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="corporate_author",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="date",
            field=models.DateField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="event_details",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="imprint",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="language",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lecture_note",
            field=models.DateTimeField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="license",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="series",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="speaker",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="speaker_details",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="sponsor",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="subject_category",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="thumbnail_picture",
            field=models.TextField(blank=True, default=""),
        ),
    ]
