# Generated by Django 3.2.8 on 2022-01-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0003_auto_20220124_1020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="speaker_details",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
