# Generated by Django 3.2.8 on 2022-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0004_auto_20220602_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="lecture_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
