# Generated by Django 3.2.8 on 2022-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0005_alter_lecture_lecture_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lecture_note",
            field=models.DateTimeField(),
        ),
    ]
