# Generated by Django 3.2.8 on 2022-07-22 09:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0007_auto_20220603_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='speaker',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=250), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='speaker_details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=250), default=list, size=None),
        ),
    ]
