# Generated by Django 3.2.8 on 2022-11-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0008_auto_20220722_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='type',
            new_name='types',
        ),
    ]
