# Generated by Django 3.2.8 on 2022-11-03 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0009_rename_type_lecture_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="video_parts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
