name: Backend

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    services:
      elasticsearch:
        image: elasticsearch:7.10.1
        env:
          bootstrap.memory_lock: true
          ES_JAVA_OPTS: -Xms1024m -Xmx1024m
          discovery.type: single-node
        ports:
          - 9200:9200

      postgresql:
        image: postgres:9.6
        env:
          POSTGRES_USER: cat
          POSTGRES_PASSWORD: cat
          POSTGRES_DB: cat
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
          poetry run python manage.py test
